using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using MyFirstWebsite.Data;
using MyFirstWebsite.Models;

namespace MyFirstWebsite.Pages.Admin.Certificates
{
    [Authorize]
    public class CreateModel : PageModel
    {
        private readonly ApplicationDbContext _context;
        private readonly IWebHostEnvironment _environment;

        public CreateModel(
            ApplicationDbContext context,
            IWebHostEnvironment environment)
        {
            _context = context;
            _environment = environment;
        }

        [BindProperty]
        public Certificate Certificate { get; set; } = new();

        [BindProperty]
        public IFormFile? ImageFile { get; set; }

        public void OnGet()
        {
            Certificate.Date = DateTime.Today;
        }

        public async Task<IActionResult> OnPostAsync()
        {
            // ImagePath is generated by the server, not entered by the user
            ModelState.Remove("Certificate.ImagePath");

            if (!ModelState.IsValid)
            {
                return Page();
            }

            if (ImageFile != null && ImageFile.Length > 0)
            {
                string uploadsFolder = Path.Combine(
                    _environment.WebRootPath,
                    "certificates");

                Directory.CreateDirectory(uploadsFolder);

                string extension = Path.GetExtension(ImageFile.FileName);
                string fileName = Guid.NewGuid().ToString() + extension;

                string filePath = Path.Combine(uploadsFolder, fileName);

                using (var stream = new FileStream(filePath, FileMode.Create))
                {
                    await ImageFile.CopyToAsync(stream);
                }

                Certificate.ImagePath = "/certificates/" + fileName;
            }
            else
            {
                Certificate.ImagePath = "";
            }

            _context.Certificates.Add(Certificate);
            await _context.SaveChangesAsync();

            return RedirectToPage("/Admin/Certificates/Index");
        }
    }
}